### ISSUE TITLE
International subsections migration

### ISSUE THREAD

**Issue by nm7582** [dx-shu/study-project#113]
Student-facing material being incorporated into Study. Need to agree and action moving others, so /international can be closed down and removed from top level nav.

- [ ] change to top level nav has backing
- [x] #117
- [x] #116
- [x] #118

No content improvement in scope, other than applicant-facing material (already being worked on as part of Study)

Working tab in build plan...

https://docs.google.com/spreadsheets/d/1qQF4HQLwaojq-v5k4V2ssWgR6X1Pw1Pg_3H5eTql7oE/edit#gid=22156562

**Comment by nm7582** [comment]
@KidRollo sorry thought I'd added you on this one too - partial answer to your question on #114

**Comment by dmdas1** [comment]
Perhaps one to pick up on in next weeks catchup @nm7582, but what is the timescale for this? Are we launching the new /study first? Or are they expecting it to be done alongside?

**Comment by nm7582** [comment]
> Perhaps one to pick up on in next weeks catchup @nm7582, but what is the timescale for this? Are we launching the new /study first? Or are they expecting it to be done alongside?

Yes, one to discuss. It's totally driven by us so there is no time expectation from any of the stakeholders mentioned above. But basically it needs to happen to follow through the logic of having international applicant material within Study, so keen to make it happen when we deploy everything else. We've also got a ton of other stuff to move on to so wary of leaving us with mop-up work a month or so down the line.

All that said - if we judge it to be unrealistic in timeframe we'll have to look at alternatives
