### ISSUE TITLE
Get extra support

### ISSUE THREAD

**Issue by Ferguson536** [dx-shu/study-project#13]
https://shu.gathercontent.com/item/14022326
Sitecore page ID: {0FB4D808-B4BC-4D78-B954-2C18968F243C}

**Comment by adalrymple13** [comment]
- [x] Page creation
- [x] Metadata
- [x] Listing summary
- [x] Page title
- [x] GatherContent

**Comment by dmdas1** [comment]
Page is in a new Bin folder. Checking with @nm7582 if still needed.

**Comment by dmdas1** [comment]
New page no longer required. Nathan: "Let's not treat this as extra page after all – SP exists in study here – we can move and implement copy improvements (though not sure PJ added much value on this one)"
