### ISSUE TITLE
QA Postgraduate section

### ISSUE THREAD

**Issue by dmdas1** [dx-shu/study-project#131]

**Comment by dmdas1** [comment]
Section ready for us to QA before it goes to stakeholders @KidRollo @nm7582:

https://www-content.shu.ac.uk/study-here/postgraduate

Note: We need to add copy to the navigation blocks to replace the lorem ipsum temporary copy.

**Comment by KidRollo** [comment]
This is looking great @dmdas1 gets my approval 👍
