### ISSUE TITLE
Keeping your data safe

### ISSUE THREAD

**Issue by Ferguson536** [dx-shu/study-project#15]
https://shu.gathercontent.com/item/14022331
Sitecore page ID: {0A3C00FD-FEF0-46BB-A381-57A47E2FAEE5}

**Comment by adalrymple13** [comment]
- [x] Page creation
- [x] Metadata
- [x] Listing summary
- [x] Page title
- [x] GatherContent

**Comment by dmdas1** [comment]
Page is in a bin folder in Sitecore. Checking with @nm7582 if still required.

**Comment by dmdas1** [comment]
No longer required. Nathan: Can bin this – link straight to privacy policy
