### ISSUE TITLE
Undergraduate

### ISSUE THREAD

**Issue by Ferguson536** [dx-shu/study-project#16]
- [x] #125
- [x] #126
- [x] #127
- [x] #128
- [x] #129

**Comment by dmdas1** [comment]
Page ID - {540B0D3E-CB6F-4680-BC13-EA8B404B6573}

- [x] Page created
- [x] Listing summary 
- [x] Metadata

**Comment by dmdas1** [comment]
Page rebuilt in new Landingpagev2 template:

https://www-content.shu.ac.uk/Study-here/undergraduate
