### ISSUE TITLE
Understanding UCAS tariffs

### ISSUE THREAD

**Issue by Ferguson536** [dx-shu/study-project#20]
https://shu.gathercontent.com/item/14022308
Sitecore ID: {E85C503F-254E-422F-B55E-E08971C034E7}

**Comment by adalrymple13** [comment]
- [x]  Page creation
- [x]  Metadata
- [x]  Listing summary
- [x]  Page title
- [ ]  GatherContent

**Comment by dmdas1** [comment]
Copy ready to add to page
