### ISSUE TITLE
UCAS deadlines

### ISSUE THREAD

**Issue by Ferguson536** [dx-shu/study-project#21]
https://shu.gathercontent.com/item/14022304
Sitecore ID: {AA31F9BF-C1C6-4D73-90B0-D938B617AB22}

**Comment by adalrymple13** [comment]
- [x] Page creation
- [x]  Metadata
- [x]  Listing summary
- [x]  Page title
- [ ]  GatherContent

**Comment by dmdas1** [comment]
Copy ready to add
