### ISSUE TITLE
Apply

### ISSUE THREAD

**Issue by Ferguson536** [dx-shu/study-project#30]
- [x] #119
- [x] #120
- [x] #121
- [x] #122
- [x] #123

**Comment by dmdas1** [comment]
Waiting on deployment to be able to build

**Comment by dmdas1** [comment]
Will need to check if SHU Progress and How to apply have have their own permissions. I don't think they do.

**Comment by dmdas1** [comment]
Deployment completed. Ready to start the build of Apply in production using the new landing page template

**Comment by dmdas1** [comment]
Landing page ID - {80E348AA-00BA-466C-A69F-F5CCFFD7B1F3}

**Comment by dmdas1** [comment]
Section built using new LandingPageV2 template. 

Now ready to begin QA @nm7582:

https://www-content.shu.ac.uk/study-here/apply

**Comment by dmdas1** [comment]
Test

**Comment by dmdas1** [comment]
Stakeholder feedback (Preview on CM):

https://docs.google.com/spreadsheets/d/1cg3VGfzEDJHaOITDsCwHNyLM2V215eYx5A59eHAfXD8/edit?usp=sharing
