### ISSUE TITLE
Apply for a postgraduate course

### ISSUE THREAD

**Issue by Ferguson536** [dx-shu/study-project#31]
https://shu.gathercontent.com/item/14022319
Sitecore page ID: {FAA29B3C-D942-42D9-870D-86525F58BADD}

**Comment by adalrymple13** [comment]
- [x]  Page creation
- [x] Metadata
- [x] Listing summary
- [x] Page title
- [x] GatherContent

**Comment by Ferguson536** [comment]
```<p>For our Masters courses, you apply direct to the University.</p>
<p>Here's a step-by-step guide to how it works.</p>

<h2>Starting your application</h2>
<p>To start an online application, find the course you want to apply for and select 'Apply now'.<p>

<p>If this is your first application, you will need to create an account. You can the start to fill in the application form. You can save your progress and come back to the form later if you need to.</p>

Find your course page [button] <!---https://www.shu.ac.uk/courses --->

<h2>When to apply</h2>
<p>You can apply at any time. There are no deadlines for masters courses, but courses do fill up, so you might have to wait for the next entry.<p> <!---https://www.shu.ac.uk/study-here/how-to-apply/international--->

<p>If you are from outside of the UK, see our how to apply information for international students.<p>

<h2>Getting an offer</h2>
<p>If your application is successful, we will make one of two kinds of offer.</p>

<p>Unconditional: Your place is already confirmed, and you don't need to meet any conditions.
Conditional: You will need to meet certain conditions before we confirm your place. 
When your place is confirmed, you're all set to start your masters. We'll send you details about what happens when you start and what you need to do next.</p>```

**Comment by Ferguson536** [comment]
`<p>For our Masters courses, you apply direct to the University.</p>
<p>Here's a step-by-step guide to how it works.</p>

<h2>Starting your application</h2>
<p>To start an online application, find the course you want to apply for and select 'Apply now'.<p>

<p>If this is your first application, you will need to create an account. You can the start to fill in the application form. You can save your progress and come back to the form later if you need to.</p>

Find your course page [button] 

<h2>When to apply</h2>
<p>You can apply at any time. There are no deadlines for masters courses, but courses do fill up, so you might have to wait for the next entry.<p>

<p>If you are from outside of the UK, see our how to apply information for international students.<p>

<h2>Getting an offer</h2>
<p>If your application is successful, we will make one of two kinds of offer.</p>

<p>Unconditional: Your place is already confirmed, and you don't need to meet any conditions.
Conditional: You will need to meet certain conditions before we confirm your place. 
When your place is confirmed, you're all set to start your masters. We'll send you details about what happens when you start and what you need to do next.</p>`

**Comment by Ferguson536** [comment]
`<p>For our Masters courses, you apply direct to the University.</p>
<p>Here's a step-by-step guide to how it works.</p>

<h2>Starting your application</h2>
<p>To start an online application, find the course you want to apply for and select 'Apply now'.<p>

<p>If this is your first application, you will need to create an account. You can the start to fill in the application form. You can save your progress and come back to the form later if you need to.</p>

Find your course page [button] 

<h2>When to apply</h2>
<p>You can apply at any time. There are no deadlines for masters courses, but courses do fill up, so you might have to wait for the next entry.<p>

<p>If you are from outside of the UK, see our how to apply information for international students.<p>

<h2>Getting an offer</h2>
<p>If your application is successful, we will make one of two kinds of offer.</p>

<p>Unconditional: Your place is already confirmed, and you don't need to meet any conditions.
Conditional: You will need to meet certain conditions before we confirm your place. 
When your place is confirmed, you're all set to start your masters. We'll send you details about what happens when you start and what you need to do next.</p>`

**Comment by dmdas1** [comment]
Copy added to page

**Comment by dmdas1** [comment]
Ready to QA
