### ISSUE TITLE
Postgraduate fees

### ISSUE THREAD

**Issue by Ferguson536** [dx-shu/study-project#33]
https://shu.gathercontent.com/item/14169865
Sitecore page ID: {DE1888E3-1878-47EB-BC87-04F40648D1DA}

**Comment by adalrymple13** [comment]
- [x] Page creation
- [x] Metadata
- [x] Listing summary
- [x] Page title
- [x] GatherContent

**Comment by Ferguson536** [comment]
<p>Our fees vary by course. Each postgraduate courses page will tell you how much tuition and any additional course costs are.</p>
Button
<p>To estimate a rough total for the whole course you should add up the tuition plus any additional costs for each year of study. </p>
<p>Remember, depending on regulations, your tuition may change a bit during your course.</p>
<h3>Annual Tuition Estimates</h3>
<h4>Postgraduate taught</h4>
<p>International Tuition 2021-22
  <br />
  £14,460-£16,070</p>
<h4>Postgraduate research</h4>
<p>See individual course pages for both home and international tuition fees</p>
<h4>MBA</h4>
<p>International Tuition 2021-22
  <br />
  £16,605</p>
<h4>PGCEs</h4>
<p>International Tuition 2021-22
  <br />
  £14,460</p>
<h4>Distance learning</h4>
<p>See individual course pages for both home and international tuition fees</p>
<h4>Home Fees</h4>
<p>If you are a 'home' student studying a postgraduate research course over more than one academic year your tuition fees could go up in later years in line with Government regulations or UK Research and Innovation (UKRI) fees. </p>
<p>More information can be found in our  under student fees regulations.</p>
<h5>EU, EEA and Swiss Nationals</h5>
<p>As of 2021, if you are a national from the EU, EEA and Switzerland not living in the UK with 'settled' or 'pre-settled' status, you are no longer eligible for home fee status and will be charged the international fee. </p>
<p>To find out more about whether you meet the residency requirements to be classified as a 'Home' student, see the Department for Education (DFE) website.</p>
<p>If you are an Irish national, you will be classified as a 'Home' student.</p>
<h4>International fees</h4>
<p>As an International student, your postgraduate tuition fees on both taught and research courses will not rise with inflation. You will pay the same tuition fee for each year of your course. </p>
<p>This doesn't apply to bench fees paid by some MPhil/PhD students, which may change during later years of your course.</p>
<h3>Additional Course Costs</h3>
<p>There are other costs associated with postsecondary education, but they vary widely between courses. To help you we made a series of tables to help you estimate these costs under the 'Fees and Funding' section of each course page. </p>
<p>Search the courses you are interested in to find our estimate tables in section 7 on each course page.</p>
<h3>Funding Support Available</h3>
<p>Find Out About Loans card/button> </p>
<p>Find Out About Scholarships and Bursaries card/button></p>

**Comment by dmdas1** [comment]
Adding HTML to page
