### ISSUE TITLE
Fees and funding

### ISSUE THREAD

**Issue by Ferguson536** [dx-shu/study-project#36]
- [x] #135

**Comment by dmdas1** [comment]
Prototype ID - {C9C68404-55E0-40C4-9D4F-79FF7113185E}
Page ID - {79502404-239B-4AAE-AC34-FDEF4C11A7DD}

**Comment by dmdas1** [comment]
Page built but needs review. Also waiting on the Funding landing as the scholarships content it points to sits within there.

**Comment by dmdas1** [comment]
https://www-content.shu.ac.uk/study-here/fees-and-funding

**Comment by dmdas1** [comment]
Page is ready to be published Friday 28 Oct
