### ISSUE TITLE
Payment methods

### ISSUE THREAD

**Issue by Ferguson536** [dx-shu/study-project#37]
https://shu.gathercontent.com/item/14022330

**Comment by Ferguson536** [comment]
<p>There are three ways you can pay your deposits and tuition fees.</p>
<h3>International payment - Flywire</h3>
<p>We have partnered with Best Price Guarantee –if you find a better exchange rate with your bank within two hours they will match it</li>
  <li>real-time payment tracking</li>
  <li>multilingual support via email, phone or live chat</li>
</ul>
<h4>Pay now with Flywire</h4>
<p>Choose one of the following to pay with Flywire.</p>
<p>[Pay your button] [Pay your Tuition Fee button]</p>
<p>To learn how to pay through Flywire, please see their virtual orientation video.</p>
<h3>Debit or credit card payments</h3>
<p>You can also pay the University directly, using our website. You may be charged for currency conversion or have to pay interest for any uncleared balance.</p>
<p>[Pay by debit/credit</a> button]</p>
<h3>Bank transfer</h3>
<p>You can also arrange a transfer through your bank. </p>
<ol>
  <li>Notify us of your intention to pay by bank transfer in your acceptance letter.</li>
  <li>Ask the bank to quote your university student reference number (from your offer letter), family name and date of birth on the transfer document.</li>
  <li>Provide the following University details to your bank.</li>
</ol>
<strong>Sort code</strong>
  <br />
  40-41-07</p>
<strong>Bank</strong>
  <br />
  HSBC Bank plc</p>
<strong>Bank address</strong>
  <br />
  Carmel House, 49-63 Fargate, Sheffield</p>
<strong>Account name</strong>
  <br />
  Sheffield Hallam University</p>
<strong>Account number</strong>

  91274163</p>
<p>Your bank may charge you for making the transfer and for currency conversion. </p>
<h2>Refunds</h2>
<p>We can refund your deposit and course fees if</p>
<ul>
  <li>your application for a student visa is refused</li>
  <li>you made an overpayment of tuition fees</li>
</ul>
<p>In both cases you will need to provide evidence to get a refund. Refunds will be made using the same method as the original payment and will be in pounds sterling. The speed of the refund will depend on the payment method you used.</p>
<h3>Refund method</h3>
<h4>Credit or debit card</h4>
<p>Refunds are made to the same credit or debit card used for payment and should be received within five working days of the transaction.</p>
<h4>Bank transfer</h4>
<p>Refunds will be made to the same bank account used for payment. We will require your account details and evidence of the payment from that account to give you a refund.</p>

**Comment by dmdas1** [comment]
Page published
