### ISSUE TITLE
Scholarships and bursaries

### ISSUE THREAD

**Issue by Ferguson536** [dx-shu/study-project#39]

**Comment by dmdas1** [comment]
Page ID - {EB698054-076B-4573-9E55-6A1923643007}

- [x] Page created
- [x] Metadata
- [x] Page title
- [x] Listing summary

**Comment by dmdas1** [comment]
Copy ready to add

**Comment by dmdas1** [comment]
Ready to add copy

**Comment by dmdas1** [comment]
Need to agree semantic tags for the listing pages
