### ISSUE TITLE
Alumni Scholarships

### ISSUE THREAD

**Issue by Ferguson536** [dx-shu/study-project#43]
https://shu.gathercontent.com/item/14182871
New Sitecore ID: {BA0B46B8-E02B-42C4-BE8F-E5A16F4A166C}

**Comment by adalrymple13** [comment]
- [x]  Page creation
- [x]  Metadata
- [x]  Listing summary
- [x]  Page title
- [ ]  GatherContent

**Comment by adalrymple13** [comment]
Agreed to create new page from scratch as redirect already required
