### ISSUE TITLE
Types of visa

### ISSUE THREAD

**Issue by dmdas1** [dx-shu/study-project#64]
Gather content: https://shu.gathercontent.com/item/14568294
Sitecore ID: {3FE7EA7A-0CDB-4361-B40B-D8CA3DFAB13A}

**Comment by adalrymple13** [comment]
- [x]  Page creation
- [ ] Metadata
- [ ] Listing summary
- [x] Page title
- [ ] GatherContent

**Comment by dmdas1** [comment]
Checked GC. Waiting on content.

**Comment by dmdas1** [comment]
Confirmed by Nathan. Page no longer required. In trash in GC.
