### ISSUE TITLE
Credibility interviews

### ISSUE THREAD

**Issue by dmdas1** [dx-shu/study-project#65]
Gather content: https://shu.gathercontent.com/item/14568297
Sitecore ID: {764CBE74-37F7-48EE-BE5B-C7EF7FBFEAFD}

**Comment by adalrymple13** [comment]
- [x]  Page creation
- [ ] Metadata
- [ ] Listing summary
- [x] Page title
- [ ] GatherContent

**Comment by dmdas1** [comment]
Checked GC. Waiting on content
