### ISSUE TITLE
Healthcare

### ISSUE THREAD

**Issue by dmdas1** [dx-shu/study-project#66]
Gather content: https://shu.gathercontent.com/item/14568306
Sitecore ID: {71233317-0BCE-4CEE-B569-BC0E0700AE19}

**Comment by adalrymple13** [comment]
- [x]  Page creation
- [x] Metadata
- [x] Listing summary
- [x] Page title
- [x] GatherContent

**Comment by dmdas1** [comment]
Checked GC. Waiting on content

**Comment by dmdas1** [comment]
Copy added to page. Ready to QA
