### ISSUE TITLE
Bringing family to Sheffield

### ISSUE THREAD

**Issue by dmdas1** [dx-shu/study-project#67]
Gather content: https://shu.gathercontent.com/item/14568296
Sitecore ID: {8570970A-01BC-4A5B-B3C3-9417583FF778}

**Comment by adalrymple13** [comment]
- [x] Page creation
- [x] Metadata
- [x] Listing summary
- [x] Page title
- [x] GatherContent

**Comment by dmdas1** [comment]
Checked GC. Waiting on content.

**Comment by dmdas1** [comment]
Copy added to page. Ready to QA.
