### ISSUE TITLE
English language requirements

### ISSUE THREAD

**Issue by dmdas1** [dx-shu/study-project#68]
Gather content: https://shu.gathercontent.com/item/14568299
Sitecore ID: {6D1E86CE-1882-4962-B9B1-20875BEA9C02}

**Comment by adalrymple13** [comment]
- [x]  Page creation
- [x] Metadata
- [x] Listing summary
- [x] Page title
- [x] GatherContent

**Comment by dmdas1** [comment]
Checked GC. Waiting on content.

**Comment by dmdas1** [comment]
Page in progress

**Comment by dmdas1** [comment]
Page copy added. Ready for QA
