### ISSUE TITLE
English language courses at Hallam

### ISSUE THREAD

**Issue by dmdas1** [dx-shu/study-project#69]
Gather content: https://shu.gathercontent.com/item/14568298 
Sitecore ID: {AAB41206-DF23-4B5C-B70B-45F151410A6D}

**Comment by adalrymple13** [comment]
- [x] Page creation
- [ ] Metadata
- [ ] Listing summary
- [x] Page title
- [ ] GatherContent

**Comment by dmdas1** [comment]
Checked GC. Waiting on content.
