### ISSUE TITLE
International qualifications

### ISSUE THREAD

**Issue by dmdas1** [dx-shu/study-project#70]
Gather Content: https://shu.gathercontent.com/item/14568303
Sitecore ID: {83BDD585-DED0-42E7-B07E-2E019C67821A}

**Comment by adalrymple13** [comment]
- [x]  Page creation
- [ ] Metadata
- [ ] Listing summary
- [x] Page title
- [ ] GatherContent

**Comment by dmdas1** [comment]
Checked GC. Waiting on content.

**Comment by dmdas1** [comment]
Confirmed by Nathan. No longer required
