### ISSUE TITLE
Arrival support

### ISSUE THREAD

**Issue by dmdas1** [dx-shu/study-project#71]
Gather content: https://shu.gathercontent.com/item/14568304
Sitecore ID: {079DDA25-4A5E-478F-9E53-3AFC7C2B93CB}

**Comment by adalrymple13** [comment]
- [x]  Page creation
- [ ] Metadata
- [ ] Listing summary
- [x] Page title
- [ ] GatherContent

**Comment by dmdas1** [comment]
Checked GC. Waiting on content
