### ISSUE TITLE
After your course

### ISSUE THREAD

**Issue by dmdas1** [dx-shu/study-project#72]
Gather content: https://shu.gathercontent.com/item/14568292
Sitecore ID: {9805BB04-C779-40AD-B2A3-876D368973CA}

**Comment by adalrymple13** [comment]
- [x]  Page creation
- [x] Metadata
- [x] Listing summary
- [x] Page title
- [x] GatherContent

**Comment by dmdas1** [comment]
Checked GC. Waiting on content

**Comment by dmdas1** [comment]
Content ready to add to page

**Comment by dmdas1** [comment]
Page built. Missing a couple of links, see GatherContent page for comments.
