### ISSUE TITLE
Accommodation for international students

### ISSUE THREAD

**Issue by dmdas1** [dx-shu/study-project#73]
Gather content: https://shu.gathercontent.com/item/14568291
Sitecore ID: {6075C460-8B72-4BF7-9FD0-F911B5A70F64}

**Comment by adalrymple13** [comment]
- [x]  Page creation
- [ ] Metadata
- [ ] Listing summary
- [x] Page title
- [ ] GatherContent

**Comment by dmdas1** [comment]
Checked GC. Waiting on content.

**Comment by dmdas1** [comment]
Confirmed by Nathan, page no longer required
