### ISSUE TITLE
Music and nightlife

### ISSUE THREAD

**Issue by dmdas1** [dx-shu/study-project#74]
Gather content: https://shu.gathercontent.com/item/14588371
Sitecore ID: {FC25F7EE-7384-4F1D-86B8-96BAEC23E236}

**Comment by adalrymple13** [comment]
- [x] Page creation
- [x] Metadata
- [x] Listing summary
- [x] Page title
- [x] GatherContent

**Comment by dmdas1** [comment]
Copy added to page

Need story card descriptions, images and a link for 'Sheffield's food scene' card
