### ISSUE TITLE
Sheffield's cost of living

### ISSUE THREAD

**Issue by dmdas1** [dx-shu/study-project#75]
Gather content: https://shu.gathercontent.com/item/14588370
Sitecore ID: {30AE65CA-8D32-40AF-A075-EA473D67DC1C}

**Comment by adalrymple13** [comment]
- [x]  Page creation
- [x] Metadata
- [x] Listing summary
- [x] Page title
- [x] GatherContent

**Comment by dmdas1** [comment]
Copy ready to add
