### ISSUE TITLE
Sheffield's food scene

### ISSUE THREAD

**Issue by dmdas1** [dx-shu/study-project#76]
Gather content: https://shu.gathercontent.com/item/14588369
Sitecore ID: {F948093E-85F1-422D-AE85-A67E83D98EDD}

**Comment by adalrymple13** [comment]
- [x]  Page creation
- [x] Metadata
- [x] Listing summary
- [x] Page title
- [x] GatherContent

**Comment by dmdas1** [comment]
Copy ready to add
