### ISSUE TITLE
Outdoor activities

### ISSUE THREAD

**Issue by dmdas1** [dx-shu/study-project#77]
Gather content: https://shu.gathercontent.com/item/14588368
Sitecore ID: {F5F74AAC-8055-4528-9DC5-27344D086878}

**Comment by adalrymple13** [comment]
- [x]  Page creation
- [x] Metadata
- [x] Listing summary
- [x] Page title
- [x] GatherContent

**Comment by dmdas1** [comment]
Copy ready to add
