### ISSUE TITLE
Arts and culture

### ISSUE THREAD

**Issue by dmdas1** [dx-shu/study-project#79]
Gather content: https://shu.gathercontent.com/item/14588379
Sitecore ID: {C54FA9DC-4A90-4CD5-890B-B13A94BFFDC2}

**Comment by adalrymple13** [comment]
- [x]  Page creation
- [x] Metadata
- [x] Listing summary
- [x] Page title
- [x] GatherContent

**Comment by dmdas1** [comment]
<p><strong>Sheffield is brimming with creativity</strong></p>

<p>You’ll find culture everywhere in Sheffield, in traditional spaces, unexpected ones and out on the street. </p>

<p>And if you're a creative yourself, you'll love the city's independent, community spirit. From sketching groups to festival volunteering, there are loads of ways to get involved.</p><h2>Visual and street art</h2>

<p>There are two major galleries right next to our City Campus. Graves Gallery is home to the city's main art collection, while Millennium Gallery has regular themed exhibitions.</p><p>You’ll also find a collection of Sheffield paintings at Weston Park Museum, a grand old building in one of the city's loveliest parks.</p>

<p>For contemporary art, try the Site Gallery or S1 Artspace. Or drop into the our own Old Post Office cafe to see exhibitions by Hallam students and researchers.</p>

<p>And while you're touring the galleries, look out for work by popular street artists such as Phlegm, Malarko and Pete McKee all over the city.</p>

<h2>Film</h2>
<p>You can catch major releases in one of several multiplex cinemas. For smaller independent films, head to the Curzon or the locally-run Showroom.</p><p>Sheffield is also home to two brilliant film festivals: Doc/Fest, the UK’s biggest documentary festival, and Sensoria, which blends cinema with live music.</p>

<p>Both have connections to our film courses, so it's common for students and researchers to get involved.</p>
<ul><li>Student society: <a href="https://www.hallamstudentsunion.com/organisation/6298/"  target="_blank" rel="noopener noreferrer">Film society</a></li>
</ul>

<h2>Theatre</h2>
<p>Sheffield Theatres is UK's largest theatre complex outside of London. It includes the award-winning Crucible, the historic Lyceum and the intimate Studio. </p>

<p>Between them, they show everything from innovative new productions to classic pantomimes.</p>

<ul>
<li>Student society: <a href="https://www.hallamstudentsunion.com/organisation/hsutheatresociety/"  target="_blank" rel="noopener noreferrer">Theatre society</a></li>
</ul>

<h2>Museums </h2>
<p>Kelham Island Museum is a superb tour of Sheffield's industrial history. Expect everything from recreated workers' houses to vast, working steam engines.  With lots of popular bars and restaurants nearby, it makes a great afternoon out.</p>
<p>Weston Park's interactive exhibitions take a different angle, looking at Sheffield's social and natural history.</p>
<p>Back in the heart of the city, you can see centuries of metalwork in the Millennium Gallery collection, or play vintage games at the National Video Game Museum. </p>
