### ISSUE TITLE
Gallery: Life in Sheffield

### ISSUE THREAD

**Issue by dmdas1** [dx-shu/study-project#80]
Gather content: https://shu.gathercontent.com/item/14588632
Sitecore ID: {9FDBA44F-0079-430B-B23E-18D92964889A}

**Comment by adalrymple13** [comment]
- [x]  Page creation
- [ ] Metadata
- [ ] Listing summary
- [x] Page title
- [ ] GatherContent

**Comment by dmdas1** [comment]
Checked GC. Waiting on content
