### ISSUE TITLE
Support for refugee students

### ISSUE THREAD

**Issue by dmdas1** [dx-shu/study-project#81]
Gather content: https://shu.gathercontent.com/item/14588378
Sitecore ID: {F9C41D77-7346-4B61-979F-C43B3051678A}

**Comment by adalrymple13** [comment]
- [x] Page creation
- [ ]  Metadata
- [ ]  Listing summary
- [x]  Page title
- [ ]  GatherContent

**Comment by dmdas1** [comment]
Checked GC. Waiting on content
