### ISSUE TITLE
Student support

### ISSUE THREAD

**Issue by dmdas1** [dx-shu/study-project#82]
Gather content: https://shu.gathercontent.com/item/14588377
Sitecore ID: {A811B077-7512-4072-8531-3979C38D5799}

**Comment by adalrymple13** [comment]
- [x] Page creation
- [ ]  Metadata
- [ ]  Listing summary
- [x]  Page title
- [ ]  GatherContent

**Comment by dmdas1** [comment]
Comment from Nathan when building:

Specialist support section
- Card grid for these – use links on 'find out more' (but obviously don't replicate the link text)

**Comment by dmdas1** [comment]
<p>We’ve worked hard to make our support both wide-ranging and easy to access. Whatever support you need, you can find it here.</p>


<h2>How we support you</h2>

<p>You’ll be able to contact a friendly helpdesk team by phone, email, web, social media and on campus. You’ll also find articles on our website that can help you find quick answers to any questions.</p>

<p>While you’re at Sheffield Hallam, you’ll always have three dedicated advisers to look out for you.</p>

<ul>
<li><strong>A student support adviser</strong> to help when outside problems affect your studies</li>
<li><strong>An academic adviser</strong> to support your learning journey.</li>
<li><strong>An employability adviser</strong> to help you choose and build the right career.</li></ul>

<p>Need something else? Speak to one of our specialist support teams to find the help you need.</p>

<h2>Specialist support</h2>
<h3>Disabilities</h3>
<p>Access to learning contracts, support, assistive technology and more. <a href="https://www.shu.ac.uk/disabled-student-support"  target="_blank" rel="noopener noreferrer">Find out more</a>.</p>

<h3>Careers</h3>
<p>Application tips, interview and career guidance, specialist advisors and help with finding jobs. <a href="https://www.shu.ac.uk/careers"  target="_blank" rel="noopener noreferrer">Find out more</a></p>

<h3>Student funding</h3>

<p>Scholarships and bursaries, money skills, support with funding issues and financial difficulties. <a href="https://www.shu.ac.uk/myhallam/support-at-hallam/student-funding"  target="_blank" rel="noopener noreferrer">Find out more</a>.</p>

<h3>International students </h3>
<p>Help and advice for international students before and after arrival, on-course support, visa queries, orientation and more. <a href="https://www.shu.ac.uk/myhallam/support-at-hallam/international-experience"  target="_blank" rel="noopener noreferrer">Find out more</a>.</p>

<h3>Wellbeing</h3>
<p>Urgent and non-urgent contact advice, self-help guidance, social events, one-to-one sessions and mental health support. <a href="https://www.shu.ac.uk/wellbeing"  target="_blank" rel="noopener noreferrer">Find out more</a>.</p>

<h3>Multi-faith chaplaincy </h3>
<p>Our chaplaincy offers pastoral care, support and guidance, worship spaces, and religious and spiritual discussions. <a href="https://www.shu.ac.uk/myhallam/support-at-hallam/multifaith-chaplaincy"  target="_blank" rel="noopener noreferrer">Find out more</a>.</p>

**Comment by dmdas1** [comment]
Used the themed nav for the card list. A dynamic nav would be restrictive in that we'd be using the listing summary copy from the source page rather than our own (unless we changed the source page).
