### ISSUE TITLE
LGBTQ+ at Hallam

### ISSUE THREAD

**Issue by dmdas1** [dx-shu/study-project#83]
Gather content: https://shu.gathercontent.com/item/14588375
Sitecore ID: {9ED5A642-3EA1-464D-AC5B-DA1FAC0EAB36}

**Comment by adalrymple13** [comment]
- [x]  Page creation
- [ ] Metadata
- [ ] Listing summary
- [x] Page title
- [ ] GatherContent

**Comment by dmdas1** [comment]
Checked GC. Waiting on content

**Comment by dmdas1** [comment]
Checked GC. Waiting on content
