### ISSUE TITLE
Student parents and carers

### ISSUE THREAD

**Issue by dmdas1** [dx-shu/study-project#84]
Gather content: https://shu.gathercontent.com/item/14588374
Sitecore ID: {F82348CB-ED2D-428A-AA19-D2A7AF937EC8}

**Comment by adalrymple13** [comment]
- [x] Page creation
- [x] Metadata
- [x] Listing summary
- [x] Page title
- [x] GatherContent

**Comment by dmdas1** [comment]
Checked GC. Waiting on content.

**Comment by dmdas1** [comment]
Page built, ready for review
