### ISSUE TITLE
Mature students at Hallam

### ISSUE THREAD

**Issue by dmdas1** [dx-shu/study-project#85]
Gather content: https://shu.gathercontent.com/item/14588373
Sitecore ID: {4BC58446-CCBC-4CD4-9C81-E838C0D4CF90}

**Comment by adalrymple13** [comment]
- [x]  Page creation
- [ ] Metadata
- [ ] Listing summary
- [x] Page title
- [ ] GatherContent

**Comment by dmdas1** [comment]
Checked GC. Waiting on content.

**Comment by dmdas1** [comment]
Content ready to add to page

**Comment by dmdas1** [comment]
Copy added to page. Ready for QA
