### ISSUE TITLE
Sport and fitness

### ISSUE THREAD

**Issue by dmdas1** [dx-shu/study-project#86]
Gather content: https://shu.gathercontent.com/item/14588366
Sitecore ID: {BA9A6AC3-0BDA-4B90-ADD1-CBF78A1D837D}

**Comment by adalrymple13** [comment]
- [x]  Page creation
- [x] Metadata
- [x] Listing summary
- [x] Page title
- [x] GatherContent

**Comment by dmdas1** [comment]
'''<p>Be inspired and stay active with top-class facilities, masses of green space and the Peak District on your doorstep.</p>

<h2>Hit the gym</h2>

<p>We have a Hallam Active gym on each campus, so it’s easy to fit in a session before or after your lectures. Students can join for as little as £14.99 a month.</p>

<p>Membership give you access to a personal trainer, free fitness classes and use of seven other sports facilities and pools across the city.</p>

<p>There's also a choice of other gyms in popular student areas of Sheffield, many with student discounts.</p>

<h3>Other ways to stay active</h3>

<p>You'll also find specialist facilities across the city, including climbing, boxing, skating, CrossFit and more. And if you're a keen swimmer, you'll love the Olympic pool at Ponds Forge – just a short walk from our City Campus.</p>

<p>Runners can join locals in Sheffield's 80 parks, and compete in everything from weekly parkrun 5ks to the famously challenging Sheffield Half-Marathon.</p>

<h2>Sports clubs</h2>
<p>We have over 40 sports clubs here at Sheffield Hallam. If you join a club, you’ll be part of Team Hallam and can take part in Varsity – our yearly tournament against the University of Sheffield.</p>```
