### ISSUE TITLE
Food and drink on campus

### ISSUE THREAD

**Issue by dmdas1** [dx-shu/study-project#87]
Gather Content: https://shu.gathercontent.com/item/14588364
Sitecore ID: {CE571A1B-C01B-4903-A1D8-32B885B44FC9}

**Comment by adalrymple13** [comment]
- [x]  Page creation
- [x] Metadata
- [x] Listing summary
- [x] Page title
- [x] GatherContent

**Comment by dmdas1** [comment]
'''<h2>Where to refuel</h2>

<p>If you need a bite to eat between lectures, our cafes across both campuses are cheap, convenient and have options to suit vegetarian, vegan, gluten-free and religious diets. Just show your SHU card for student discount.</p>

<p>All the money we make from food on-site goes back into the university so we can keep improving your student experience.</p>

<h2>A proper meal</h2> 

<p>Our Hallam Kitchen restaurants serve up healthy breakfasts and lunches, with everything from granola to salads and open sandwiches on the menu.</p> 

<p>There are three Hallam Kitchens on campus, including one with table service for a more relaxed experience.</p>

<h2>A quick bite</h2>
<p>Our eight Hallam Cafes are perfect for drinks and snacks on the go. Grab a meal deal for £3.50 at any of our cafes. They include homemade sandwiches, snacks and drinks. </p>

<p>You can also get hot and cold drinks and snacks at most vending machines across City and Collegiate campuses. They are ideal for a quick pick-me-up.</p>

<h2>Sustainability </h2>
<p>Our cafes make every effort to be sustainable. We have a bio-digester on-site and give out reusable cups every year, plus discounts when you use your own cup. We’re also trialling plastic-free cafes. </p>

<p>We also work with local suppliers, sourcing everything from milk to chocolate from independent Sheffield-based businesses. </p>```

**Comment by dmdas1** [comment]
Need:

- Links / CTA?
- Related content?
