### ISSUE TITLE
Gallery: Our campus

### ISSUE THREAD

**Issue by dmdas1** [dx-shu/study-project#88]
Gather content: https://shu.gathercontent.com/item/14588624
Sitecore ID: {6644A56B-F873-4EC7-830C-4AD22B92781B}

**Comment by adalrymple13** [comment]
- [x] Page creation
- [ ] Metadata
- [ ] Listing summary
- [x] Page title
- [ ] GatherContent

**Comment by dmdas1** [comment]
Checked GC. Waiting on content.
