### ISSUE TITLE
Clubs and societies

### ISSUE THREAD

**Issue by dmdas1** [dx-shu/study-project#89]
Gather content: https://shu.gathercontent.com/item/14588361
Sitecore: {DE697E7B-1022-4B6D-BF0C-A59AF24F0C5A}

**Comment by adalrymple13** [comment]
- [x] Page creation
- [x]  Metadata
- [x]  Listing summary
- [x]  Page title
- [ ]  GatherContent

**Comment by dmdas1** [comment]
<p><strong>Do more of what you love</strong></p>

<p>Make friends for life. Have a go at something new. Or simply spend your free time doing more of the hobbies and passions you enjoy. It all happens at our clubs and societies.</p>

<p>Our union has over 100 student-run societies for everything from surfing to sustainability. And they’re all free or affordable to join.</p>

<p>They cover a huge range of interests in culture, faith, active hobbies, performance, media, creative arts, politics, campaigning and volunteer projects. There are also societies for academic subjects, which can be useful networks through your studies.</p>

<p>And if you feel something is missing, you can create your own! New societies are added to our list every year.</p>

<h2>Find the society for you</h2>
<p>[Social societies]</p><p>[Academic societies]</p>
