### ISSUE TITLE
Our student community

### ISSUE THREAD

**Issue by dmdas1** [dx-shu/study-project#91]
Gather content: https://shu.gathercontent.com/item/14588376
Sitecore page ID: {21779AF6-D56B-4164-9ECE-CE6F0094F787}

**Comment by adalrymple13** [comment]
- [x] Page creation
- [ ] Metadata
- [ ] Listing summary
- [x] Page title
- [ ] GatherContent

**Comment by dmdas1** [comment]
Checked GC. Waiting on content
