### ISSUE TITLE
Working while you study

### ISSUE THREAD

**Issue by dmdas1** [dx-shu/study-project#93]
Gather content: https://shu.gathercontent.com/item/14588372
Sitecore ID: {50CC5B59-F44B-4614-9DEE-4C088F2938BA}

**Comment by adalrymple13** [comment]
- [x] Page creation
- [x] Metadata
- [x] Listing summary
- [x] Page title
- [x] GatherContent

**Comment by dmdas1** [comment]
<p><strong>Getting the balance right</strong></p>
<p>A lot of our students work part-time while at university. Not only will a part-time job bring in extra money, but it can also look great on your CV. </p>

<p>We can help you find a job that suits your timetable and will impress employers when you graduate.</p><h2>Finding a part-time job</h2>

<p>Sheffield is at its busiest when there are thousands of students living here, so lots of local businesses have jobs during term time. We have ties with different businesses and can connect you to roles they have on offer.</p>
<p>It’s all done through a platform called Handshake, and we’ll help you with applying for the roles that suit you best.</p>

<h2>Jobs on campus</h2>
<p>We also offer part-time and casual jobs at the University. That could be in our kitchens, at events and open days, or supporting on research projects for example.</p>
<p>Some of these roles need specific skills, so they can be a good opportunity to gain valuable work experience. </p>
<p>Our campus jobs are advertised on Handshake too, so you only need to look in one place to see vacancies.</p>
<h2>Freelancing</h2>
<p>Freelancing can be a great way to showcase your skills to employers and gain experience, all while getting paid for each job you do.</p>
<p>We connect students with businesses in the area through our own platform, Hallam Freelancers. This type of work can be particularly useful for students working towards creative degrees, like writing, design, film making and photography.</p>
<h2>Working as an international student</h2>
<p>If you are an international student on a tier four visa, you can work while you study up to a set number of hours a week. You can check the rules at ukcisa.org.uk.</p>

**Comment by dmdas1** [comment]
Copy added to page.

No related links provided. Left the component off for now.
