### ISSUE TITLE
Overseas travel

### ISSUE THREAD

**Issue by dmdas1** [dx-shu/study-project#94]
Gather content: https://shu.gathercontent.com/item/14588362
Sitecore ID: {BEEE1725-8B6E-4F14-961F-9684C053BA56}

**Comment by adalrymple13** [comment]
- [x]  Page creation
- [x] Metadata
- [x] Listing summary
- [x] Page title
- [x] GatherContent

**Comment by dmdas1** [comment]
<p><strong>Study or travel? Do both</strong></p>

<p>University is a great time to expand your horizons. Overseas experiences allow you to learn about different cultures, practise your language skills and make friends across the world.</p>
<p>Our GoGlobal programme helps you travel while you study. Through GoGlobal, you can take part in:</p>

<ul>
  <li>study and field trips</li>
  <li>semesters studying at a partner university</li>
  <li>volunteering programmes</li>
  <li>internships and summer work placements</li>
</ul>

<h2><strong>Opening doors for everyone</strong></h2>
<p>GoGlobal opportunities are open to all students, no matter which course you are studying. You can also apply for funding for trips you manage yourself.</p>
<p>Our overseas experiences are designed for personal development, and you can add them to your record of achievement through the Hallam Award. It's a great way to develop an international perspective and to show employers there is more to you than your degree.</p>

<h2><strong>Global life in Sheffield</strong></h2>
<p>We have students from more than 100 countries at Sheffield Hallam, and we find ways to bring people with different nationalities together.</p>

<p>We host activities and events all year round, even during holidays. Or you can volunteer as a 'Culture Connect' mentor to help new students make the most of life in Sheffield. These opportunities give you first-hand insight into different cultures and global perspectives.</p>
<p>[Links]</p>

**Comment by dmdas1** [comment]
Copy added to page

Missing links in the copy (see bottom of page)
