### ISSUE TITLE
Apply through an agent

### ISSUE THREAD

**Issue by dmdas1** [dx-shu/study-project#95]
Gather content: https://shu.gathercontent.com/item/14568293
Sitecore ID: {608789F8-607B-49E8-8C79-1C763CA1CD7C}

**Comment by adalrymple13** [comment]
- [x]  Page creation
- [ ] Metadata
- [ ] Listing summary
- [x] Page title 
- [ ] GatherContent

**Comment by dmdas1** [comment]
Checked GC. Waiting on content.

**Comment by dmdas1** [comment]
Copying HTML from https://www2.shu.ac.uk/services/ssc/international/agents.cfm?

**Comment by dmdas1** [comment]
Unable to proceed with current code. The page uses coldfusion code to dynamically show/hide agent contact details.

Nathan checking with Helen Morecroft if they have a simple list we can use.
