### ISSUE TITLE
Events in your country

### ISSUE THREAD

**Issue by dmdas1** [dx-shu/study-project#96]
Gather content: https://shu.gathercontent.com/item/14568300
Sitecore ID: {118BB581-D0AE-4299-A795-0D023438AC92}

**Comment by adalrymple13** [comment]
- [x]  Page creation
- [ ] Metadata
- [ ] Listing summary
- [x] Page title
- [ ] GatherContent

**Comment by dmdas1** [comment]
Checked GC. Waiting on content.

**Comment by dmdas1** [comment]
Page is in trash in GC.

Confirmed by Nathan, no longer required.
