### ISSUE TITLE
Find your country office

### ISSUE THREAD

**Issue by dmdas1** [dx-shu/study-project#97]
Gather content: (https://shu.gathercontent.com/item/14568301)
Sitecore ID: {67F14EF2-B57F-4530-81AA-4A9BEE79A933}

**Comment by adalrymple13** [comment]
- [x]  Page creation
- [ ] Metadata
- [ ] Listing summary
- [x] Page title
- [ ] GatherContent

**Comment by dmdas1** [comment]
Checked GC. Waiting on content
