### ISSUE TITLE
International fees

### ISSUE THREAD

**Issue by dmdas1** [dx-shu/study-project#98]
Gather content: https://shu.gathercontent.com/item/14568302
Sitecore ID: {EE4010EA-881B-4146-A354-61DA42B58188}

**Comment by adalrymple13** [comment]
- [x] Page creation
- [ ] Metadata
- [ ] Listing summary
- [x] Page title
- [ ] GatherContent

**Comment by nm7582** [comment]
@dmdas1 @Ferguson536 thinking now is the international fees page can do one – better to incorporate both home and international into the relevant level-specific fee pages. Is there a 'cancelled' status in here or do we just delete?

**Comment by Ferguson536** [comment]
Move to done

**Comment by nm7582** [comment]
Done
