### ISSUE TITLE
Tuition fee deposits

### ISSUE THREAD

**Issue by dmdas1** [dx-shu/study-project#99]
Gather content: https://shu.gathercontent.com/item/14568305
Sitecore ID: {062883D5-0B21-4B7C-9B5E-0A4B2602A006}

**Comment by adalrymple13** [comment]
- [x]  Page creation
- [ ]  Metadata
- [ ]  Listing summary
- [x]  Page title
- [ ]  GatherContent

**Comment by dmdas1** [comment]
Checked GC. Waiting on content
